AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'

Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: either
Style/StringLiterals:
  Enabled: false
